version: '3.6'

services:
  
  mongo-db:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27020:27017
      
  lepus-api-nova: 
    image: lepus-api-nova:dev
    build:
      context: ./API/API/Lepus/Lepus.API/
    container_name: "lepus-api-nova" 
    ports:
      - 5005:80 
    depends_on:
      - mongo-db

  lepus-app: 
    image: lepus-app:dev
    build:
      context: ./APP/
    container_name: "lepus-app"
    ports:
      - 4200:4200 
    depends_on:
      - lepus-api-nova 
 