version: '3.6'

services:
  
  mongo-db:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017
      
  lepus-api: 
    image: lepus-api 
    build:
      context: ./API/
    container_name: "lepus-api"
    ports:
      - 80 
    depends_on:
      - mongo-db

  lepus-app: 
    image: lepus-app 
    build:
      context: ./APP/
    container_name: "lepus-app"
    ports:
      - 4200 
    depends_on:
      - lepus-api 

  reverse-proxy:
    image: nginx:latest
    build:
      context: ./ReverseProxy/
    ports:
    - 9090:80
    - 9443:443
    depends_on:
    - lepus-api
    - lepus-app
  
